/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab5P2_BoniehtRamirez;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        jmenu_modificar = new javax.swing.JMenuItem();
        jmenu_listar = new javax.swing.JMenuItem();
        jmenu_eliminar = new javax.swing.JMenuItem();
        jDialog_Modificar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_nombreModificar = new javax.swing.JTextField();
        jt_apellidoModificar = new javax.swing.JTextField();
        jt_nacionalidadModificar = new javax.swing.JTextField();
        sp_edadModificar = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        JDialog_CrearJugador = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_nombreJugador = new javax.swing.JTextField();
        jt_nacionalidadJugador = new javax.swing.JTextField();
        jt_apellidoJugador = new javax.swing.JTextField();
        sp_edadJugador = new javax.swing.JSpinner();
        sp_duracionJugador = new javax.swing.JSpinner();
        sp_numeroJugador = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jDialog_ListarJugador = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jmenu_modificar.setText("Modificar");
        jmenu_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_modificarActionPerformed(evt);
            }
        });
        popupmenu.add(jmenu_modificar);

        jmenu_listar.setText("Listar");
        jmenu_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_listarActionPerformed(evt);
            }
        });
        popupmenu.add(jmenu_listar);

        jmenu_eliminar.setText("Eliminar");
        jmenu_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_eliminarActionPerformed(evt);
            }
        });
        popupmenu.add(jmenu_eliminar);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nacionalidad:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");

        sp_edadModificar.setModel(new javax.swing.SpinnerNumberModel(18, 18, 50, 1));

        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog_ModificarLayout = new javax.swing.GroupLayout(jDialog_Modificar.getContentPane());
        jDialog_Modificar.getContentPane().setLayout(jDialog_ModificarLayout);
        jDialog_ModificarLayout.setHorizontalGroup(
            jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ModificarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jt_nombreModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jt_apellidoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jt_nacionalidadModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(sp_edadModificar))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jDialog_ModificarLayout.setVerticalGroup(
            jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ModificarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_apellidoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_nacionalidadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sp_edadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Apellido:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Nacionalidad:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Número:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Edad:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Años Contrato:");

        sp_edadJugador.setModel(new javax.swing.SpinnerNumberModel());

        sp_duracionJugador.setModel(new javax.swing.SpinnerNumberModel());

        sp_numeroJugador.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JDialog_CrearJugadorLayout = new javax.swing.GroupLayout(JDialog_CrearJugador.getContentPane());
        JDialog_CrearJugador.getContentPane().setLayout(JDialog_CrearJugadorLayout);
        JDialog_CrearJugadorLayout.setHorizontalGroup(
            JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_CrearJugadorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_nombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(jt_nacionalidadJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(jt_apellidoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(sp_edadJugador)
                        .addComponent(sp_numeroJugador)
                        .addComponent(sp_duracionJugador)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        JDialog_CrearJugadorLayout.setVerticalGroup(
            JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_CrearJugadorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_apellidoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_nacionalidadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_edadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JDialog_CrearJugadorLayout.createSequentialGroup()
                        .addGroup(JDialog_CrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(sp_numeroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(sp_duracionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
        );

        jList.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jList);

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel11.setText("JLIST");

        javax.swing.GroupLayout jDialog_ListarJugadorLayout = new javax.swing.GroupLayout(jDialog_ListarJugador.getContentPane());
        jDialog_ListarJugador.getContentPane().setLayout(jDialog_ListarJugadorLayout);
        jDialog_ListarJugadorLayout.setHorizontalGroup(
            jDialog_ListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ListarJugadorLayout.createSequentialGroup()
                .addGroup(jDialog_ListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_ListarJugadorLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel11))
                    .addGroup(jDialog_ListarJugadorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jDialog_ListarJugadorLayout.setVerticalGroup(
            jDialog_ListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ListarJugadorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jugadores");
        treeNode1.add(treeNode2);
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        jButton2.setText("Crear Jugador");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Jugar Partido", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Terapia Psicologica", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
        if(evt.getButton()!=1){
            if(jTree.getSelectionCount()!=0)
                popupmenu.show(evt.getComponent(), evt.getX(), evt.getY());                                      
        }            
    }//GEN-LAST:event_jTreeMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        nodoSeleccionado = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
        Persona p = (Persona)nodoSeleccionado.getUserObject();
        p.setNombre(jt_nombreModificar.getText());
        p.setApellido(jt_apellidoModificar.getText());
        p.setNacionalidad(jt_nacionalidadModificar.getText());
        p.setEdad((int)sp_edadModificar.getValue());
                
        JOptionPane.showMessageDialog(jDialog_Modificar,"jugador modificado");
        
        jDialog_Modificar.setVisible(false);
        
        jt_nombreModificar.setText("");
        jt_apellidoModificar.setText("");
        jt_nacionalidadModificar.setText("");
        sp_edadModificar.setValue(18);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JDialog_CrearJugador.pack();
        JDialog_CrearJugador.setLocationRelativeTo(this);
        JDialog_CrearJugador.setModal(true);
        JDialog_CrearJugador.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        nodoSeleccionado = (DefaultMutableTreeNode) jTree.getPathForRow(1).getLastPathComponent();
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode();
        nodo.setUserObject(jt_nombreJugador.getText());
        nodo.setUserObject(new Jugador((int)sp_numeroJugador.getValue(),(int)sp_duracionJugador.getValue(),jt_nombreJugador.getText(),jt_apellidoJugador.getText(),jt_nacionalidadJugador.getText(),(int)sp_edadJugador.getValue()));
        
        nodoSeleccionado.add(nodo);
        
        JOptionPane.showMessageDialog(JDialog_CrearJugador, "jugador creado");
        
        sp_numeroJugador.setValue(0);
        sp_edadJugador.setValue(0);
        sp_duracionJugador.setValue(0);
        jt_nombreJugador.setText("");
        jt_apellidoJugador.setText("");
        jt_nacionalidadJugador.setText("");
        JDialog_CrearJugador.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jmenu_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_modificarActionPerformed
        jDialog_Modificar.pack();
        jDialog_Modificar.setModal(true);
        jDialog_Modificar.setLocationRelativeTo(this);
        jDialog_Modificar.setVisible(true);
    }//GEN-LAST:event_jmenu_modificarActionPerformed

    private void jmenu_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_eliminarActionPerformed
        nodoSeleccionado = (DefaultMutableTreeNode) jTree.getSelectionPath().getLastPathComponent();
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
        model.removeNodeFromParent(nodoSeleccionado);
    }//GEN-LAST:event_jmenu_eliminarActionPerformed

    private void jmenu_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_listarActionPerformed
        nodoSeleccionado = (DefaultMutableTreeNode) jTree.getSelectionPath().getLastPathComponent();
        Persona p = (Persona)nodoSeleccionado.getUserObject();
        DefaultListModel model = new DefaultListModel();
        model.addElement("Nombre: "+((Jugador)p).getNombre());
        model.addElement("Apellido: "+((Jugador)p).getApellido());
        model.addElement("Pais: " + ((Jugador)p).getNacionalidad());
        model.addElement("Edad: " + ((Jugador)p).getEdad());
        model.addElement("Número: " + ((Jugador)p).getNumero());
        model.addElement("Años de contrato: " + ((Jugador)p).getDuracionContrato());
        model.addElement("Partidos Jugados: " + ((Jugador)p).getPartidosJugados());
        model.addElement("Tarjetas Amarillas: " + ((Jugador)p).getTarjetasAmarillas());
        model.addElement("Tarjetas Rojas: " + ((Jugador)p).getTarjetasRojas());
        model.addElement("Copas Ganadas:  " + ((Jugador)p).getCopasGanadas());

        jList.setModel(model);
        
        jDialog_ListarJugador.pack();
        jDialog_ListarJugador.setModal(true);
        jDialog_ListarJugador.setLocationRelativeTo(this);
        jDialog_ListarJugador.setVisible(true);
    }//GEN-LAST:event_jmenu_listarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialog_CrearJugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog_ListarJugador;
    private javax.swing.JDialog jDialog_Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JMenuItem jmenu_eliminar;
    private javax.swing.JMenuItem jmenu_listar;
    private javax.swing.JMenuItem jmenu_modificar;
    private javax.swing.JTextField jt_apellidoJugador;
    private javax.swing.JTextField jt_apellidoModificar;
    private javax.swing.JTextField jt_nacionalidadJugador;
    private javax.swing.JTextField jt_nacionalidadModificar;
    private javax.swing.JTextField jt_nombreJugador;
    private javax.swing.JTextField jt_nombreModificar;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JSpinner sp_duracionJugador;
    private javax.swing.JSpinner sp_edadJugador;
    private javax.swing.JSpinner sp_edadModificar;
    private javax.swing.JSpinner sp_numeroJugador;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodoSeleccionado;

}
